name: Run Container

on:
  push:
    branches:
      - main

jobs:
  run-container:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/takeshiemoto/my-docker-image:sha-4e52f3a@sha256:24dc8e6f8bf105da00ff076615d0ebf6ac05abce690bd0269951f00303917353

    steps:
      - name: Run a script inside the container
        run: |
          echo "Hello, World!"