name: Run Container

on:
  push:
    branches:
      - main

jobs:
  run-container:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/takeshiemoto/my-docker-image:main@sha256:0b27079378f8bb32058320098c68772bbf54f744f1bcfdbdb23e2665c5bdc239

    steps:
      - name: Run a script inside the container
        run: |
          echo "Hello, World!"